# The Perceptron Algorithm

In this Jupyter notebook, we will implement the perceptron algorithm written with Python utilizing the [iris dataset](https://en.wikipedia.org/wiki/Iris_flower_data_set).

Contrary to the [Julia](https://github.com/jzhu95/DATA_4319/blob/master/Julia/Perceptron_Learning_Julia/Perceptron.ipynb) perceptron algorithm where we wrote every function and tested the data ourselves, we will utilize the package of scikit-learn, or sklearn.

We will also implement the following packages: 
* scikit-learn [documentation](https://github.com/scikit-learn/scikit-learn)
* numpy [documentation](https://github.com/numpy/numpy)

The perceptron algorithm is utilized for the supervised learning of binary classifiers (meaning its task is to classify the elements of a set into two groups on the basis of the classification rule). It is also a single-layer neural network consisting of four main parts: input values, weights and bias, net sum, and an activation function.

![Perceptron](perceptronTheory.png)


### Load and View Data

In [9]:
# Load required libraries
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

In [10]:
# Load the iris dataset
iris = datasets.load_iris()

# Create our X and y data
X = iris.data
y = iris.target

In [11]:
# View the first five observations of our y data
y[:5]

array([0, 0, 0, 0, 0])

In [12]:
# View the first five observations of our x data.
# Notice that there are four independent variables (features)
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

### Split The Iris Data Into Training And Test

In [13]:
# Split the data into 70% training data and 30% test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

### Preprocess The X Data By Scaling

Data preprocessing is an extremely important step in machine learning or deep learning. We cannot just dump the raw data into a model and expect it to perform well. Even if we build a complex, well structured model, its performance gets as good as the data we feed to it. If we use them without any scaling, machine learning models might give more importance to the features with higher values. Models tend to perform better and converge faster when the features are on a relatively similar scale. Thus, we need to process the raw data to boost the performance of models.

In [14]:
# Train the scaler, which standarizes all the features to have mean=0 and unit variance
sc = StandardScaler()
sc.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [15]:
# Apply the scaler to the X training data
X_train_std = sc.transform(X_train)

# Apply the SAME scaler to the X test data
X_test_std = sc.transform(X_test)

### Train A Perceptron Learner

In [17]:
# Create a perceptron object with the parameters: learning rate of 0.1, tolerance of 0.001
ppn = Perceptron(tol = .001, eta0=0.1, random_state=0)

# Train the perceptron
ppn.fit(X_train_std, y_train)

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=0.1,
           fit_intercept=True, max_iter=1000, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=0, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

### Apply The Trained Learner To Test Data

In [18]:
# Apply the trained perceptron on the X data to make predicts for the y test data
y_pred = ppn.predict(X_test_std)

In [19]:
# View the predicted y test data
y_pred

array([0, 1, 1, 0, 2, 2, 2, 0, 0, 2, 2, 2, 0, 2, 0, 0, 2, 2, 2, 1, 2, 2,
       2, 1, 0, 0, 1, 2, 2, 1, 0, 1, 2, 1, 2, 0, 2, 2, 0, 0, 0, 0, 2, 2,
       0])

### Compare The Predicted Y With The True Y

In [20]:
# View the true y test data
y_test

array([0, 1, 1, 0, 2, 2, 2, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2,
       1, 1, 0, 0, 1, 2, 2, 0, 0, 1, 2, 1, 2, 0, 1, 1, 0, 0, 0, 0, 2, 2,
       0])

### Examine Accuracy Metric

In [21]:
# View the accuracy of the model, which is: 1 - (observations predicted wrong / total observations)
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

Accuracy: 0.84
